-- Natural-key checks work even on older tables that do not yet have a unique constraint.
insert into public.settings(key,value,status) select v.key,v.value::jsonb,v.status from (values ('site','{"siteName":"ICON EDITZ","currency":"INR"}','published'),('analytics','{}','published'),('admin_setup','{"instructions":"Create an Auth user, then insert its id into public.admins."}','published')) v(key,value,status) where not exists (select 1 from public.settings s where s.key=v.key);
insert into public.r2_buckets(bucket_name,status) select 'icon-editz-assets','active' where not exists (select 1 from public.r2_buckets where bucket_name='icon-editz-assets');
insert into public.footer_content(id,content,status) select true,'{"brandName":"ICON EDITZ","description":"Creative editing, motion, and digital assets.","quickLinks":[],"socialLinks":{}}','published' where not exists (select 1 from public.footer_content where id=true);
insert into public.cta_content(id,content,status) select true,'{"heading":"Let us build your next creative project.","visible":true}','published' where not exists (select 1 from public.cta_content where id=true);
insert into public.legal_pages(title,content,slug,published,status) select v.title,v.content,v.slug,true,'published' from (values ('Privacy Policy','Privacy policy content will be published here.','privacy-policy'),('Terms of Service','Terms of service content will be published here.','terms-of-service')) v(title,content,slug) where not exists (select 1 from public.legal_pages p where p.slug=v.slug);
insert into public.page_content(page,section,content,status,sort_order) select v.page,v.section,'{}','published',v.sort_order from (values ('Homepage','Hero',0),('Homepage','About',1),('Homepage','Services',2),('Homepage','Projects',3),('Homepage','Store',4),('Homepage','Footer',5),('Homepage','CTA',6),('Homepage','Legal',7),('About','Hero',0),('Services','Hero',0),('Projects','Hero',0),('Store','Hero',0),('Hire From Us','Hero',0)) v(page,section,sort_order) where not exists (select 1 from public.page_content p where p.page=v.page and p.section=v.section);
insert into public.website_sections(page,section_key,content,status,sort_order) select v.page,v.section_key,v.content::jsonb,'published',v.sort_order from (values ('Hire From Us','hero','{}',0),('Hire From Us','enquiry_form','{}',1),('Hire From Us','contact','{}',2),('Hire From Us','social','{}',3),('Hire From Us','seo','{}',4),('Hire From Us','features','{"items":[]}',5),('Hire From Us','services','{"items":[]}',6),('Hire From Us','gallery','{"items":[]}',7),('Hire From Us','faq','{"items":[]}',8)) v(page,section_key,content,sort_order) where not exists (select 1 from public.website_sections s where s.page=v.page and s.section_key=v.section_key);
insert into public.profiles(id,display_name,status) select u.id,coalesce(u.raw_user_meta_data->>'full_name',u.email),'active' from auth.users u where not exists (select 1 from public.profiles p where p.id=u.id) order by u.created_at limit 1;
insert into public.admins(user_id,role,status) select u.id,'admin','active' from auth.users u where not exists (select 1 from public.admins a where a.user_id=u.id) order by u.created_at limit 1;
