-- Idempotent public CMS seed. Content is stored in Supabase, never read from frontend data files.
insert into public.page_content(page,section,content,status,sort_order)
select v.page,v.section,v.content::jsonb,'published',v.sort_order
from (values
  ('Homepage','Hero',$${"heading":"ICON EDITZ","subtitle":"Motion Graphics • Video Editing • Branding • Creative Assets","description":"Premium visual storytelling for modern brands, creators, and ambitious launches built with cinematic pacing and refined motion.","primaryCta":"Explore Projects","primaryHref":"/projects","secondaryCta":"Hire Me","secondaryHref":"/hire","badges":["Cinematic edits","Fast delivery","Brand-ready assets"]}$$,0),
  ('Homepage','Showreel',$${"title":"Creative Showreel","description":"A refined preview of premium editing, motion graphics, and brand-focused storytelling.","videoUrl":"/assets/videos/3d-lyrics-video-1.mp4","thumbnail":"/assets/images/og-icon-editz.png","buttonText":"Watch More"}$$,1),
  ('Homepage','Projects',$${"items":[{"id":"project-1","title":"Cinematic Lyric Story","category":"Motion Graphics","description":"A premium lyric visual driven by motion, rhythm, and clean typography.","thumbnail":"/assets/images/og-icon-editz.png","tags":["Motion Graphics"],"visible":true},{"id":"project-2","title":"Wedding Highlight Reel","category":"Wedding Films","description":"A romantic edit with polished pacing and emotional storytelling.","thumbnail":"/assets/images/og-icon-editz.png","tags":["Wedding Films"],"visible":true}]}$$,2),
  ('Homepage','Tools',$${"items":[{"id":"premiere","name":"Adobe Premiere Pro","description":"Professional editing and narrative pacing.","percentage":95,"icon":"Film","visible":true},{"id":"after-effects","name":"After Effects","description":"Motion graphics and animated brand systems.","percentage":92,"icon":"Sparkles","visible":true}]}$$,3),
  ('Homepage','Testimonials',$${"items":[{"id":"testimonial-1","name":"Sai Kumar","company":"Music Creator","review":"Every frame felt intentional. The pacing and polish were exactly what we needed.","rating":5,"visible":true}]}$$,4),
  ('Homepage','FAQ',$${"items":[{"id":"faq-1","question":"How long does editing take?","answer":"Timelines depend on scope and are agreed before production begins.","visible":true}]}$$,5),
  ('Homepage','Featured Services',$${"label":"Featured Services","heading":"Creative support for every big idea","description":"A focused selection of our most requested creative services.","buttonText":"View All Services","buttonUrl":"/services","buttonVisible":true}$$,6),
  ('Services Page','Services',$${"hero":{"label":"SERVICES","heading":"Creative Services That Help Brands Stand Out","description":"Premium video editing, motion graphics, branding, and social content for creators and businesses.","primaryCta":"Hire From Us","primaryHref":"/hire","secondaryCta":"View Projects","secondaryHref":"/projects","visible":true},"services":[{"id":"video-editing","title":"Video Editing","description":"Cinematic stories with confident pacing and polished finishing.","features":["Cinematic editing","Reels, YouTube & corporate"],"price":"From ₹1,999","visible":true,"featured":true},{"id":"motion-graphics","title":"Motion Graphics","description":"Animated typography and visuals built to hold attention.","features":["Titles & transitions","Branded motion"],"price":"From ₹2,999","visible":true,"featured":true}],"process":[],"features":[],"industries":[],"software":[],"packages":[],"faq":[],"testimonials":[],"cta":{"visible":false}}$$,0),
  ('About Page','Hero',$${"eyebrow":"About","heading":"About Icon Editz","description":"A creative studio focused on premium editing, motion graphics, and visual storytelling."}$$,0),
  ('Projects Page','Hero',$${"eyebrow":"Projects","heading":"Featured Projects","description":"Selected creative work from Icon Editz."}$$,0),
  ('Projects Page','Projects',$${"items":[{"id":"project-1","title":"Cinematic Lyric Story","category":"Motion Graphics","description":"A premium lyric visual driven by motion, rhythm, and clean typography.","tags":["Motion Graphics"],"visible":true},{"id":"project-2","title":"Wedding Highlight Reel","category":"Wedding Films","description":"A romantic edit with polished pacing and emotional storytelling.","tags":["Wedding Films"],"visible":true}]}$$,1),
  ('Store Page','Hero',$${"eyebrow":"Store","heading":"Premium creative assets","description":"Templates, edits, presets, and creative tools for your next project."}$$,0),
  ('Store Page','SEO',$${"title":"Icon Editz Store","description":"Premium creative assets from Icon Editz."}$$,1)
) as v(page,section,content,sort_order)
where not exists (select 1 from public.page_content p where p.page=v.page and p.section=v.section);

insert into public.footer_content(id,content,status)
select true,$${"brandName":"ICON EDITZ","description":"Creative editing, motion, and digital assets.","quickLinks":[{"label":"Home","url":"/"},{"label":"Services","url":"/services"},{"label":"Store","url":"/store"}],"socialLinks":{},"copyrightText":"© Icon Editz. All rights reserved."}$$::jsonb,'published'
where not exists (select 1 from public.footer_content where id=true);
insert into public.cta_content(id,content,status)
select true,$${"heading":"Let us build your next creative project.","subheading":"Bring your next launch, campaign, or story to life.","primaryButton":"Hire Me","primaryButtonUrl":"/hire","secondaryButton":"View Store","secondaryButtonUrl":"/store","visible":true}$$::jsonb,'published'
where not exists (select 1 from public.cta_content where id=true);
