import React, { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { FaFacebookF, FaInstagram, FaLinkedinIn, FaXTwitter, FaYoutube } from 'react-icons/fa6'
import { supabase } from '../utils/supabase'

const socialIcons = { youtube: FaYoutube, instagram: FaInstagram, facebook: FaFacebookF, linkedin: FaLinkedinIn, twitter: FaXTwitter }

export default function Footer() {
  const [content, setContent] = useState(null); const [email, setEmail] = useState(''); const [notice, setNotice] = useState('')
  useEffect(() => { if (!supabase) return; supabase.from('footer_content').select('content').eq('id', true).maybeSingle().then(({ data, error }) => { if (error) setNotice(error.message); else setContent(data?.content || null) }) }, [])
  const subscribe = async (event) => { event.preventDefault(); if (!supabase) return setNotice('Newsletter is unavailable until Supabase is configured.'); setNotice(''); const { error } = await supabase.from('newsletter_subscribers').insert({ email }); if (error) setNotice(error.message); else { setEmail(''); setNotice('Subscribed successfully.') } }
  if (!content) return null
  return <footer style={{ backgroundColor: content.backgroundColor, '--footer-accent': content.accentColor || '#8b5cf6' }} className="border-t border-white/10 text-white"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-16 sm:grid-cols-2 lg:grid-cols-4 lg:px-8"><div><div className="flex items-center gap-3">{content.logo && <img src={content.logo} alt={content.brandName || 'ICON EDITZ'} className="h-11 w-11 rounded-xl object-cover"/>}<h2 className="text-xl font-bold">{content.brandName || 'ICON EDITZ'}</h2></div><p className="mt-5 max-w-xs text-sm leading-7 text-white/60">{content.description}</p><div className="mt-6 flex gap-3">{Object.entries(content.socialLinks || {}).filter(([name, url]) => url && socialIcons[name]).map(([name, url]) => { const Icon = socialIcons[name]; return <a key={name} href={url} target="_blank" rel="noreferrer" className="grid h-9 w-9 place-items-center rounded-full border border-white/10 text-white/70 transition hover:border-[var(--footer-accent)] hover:text-white"><Icon /></a> })}</div></div><div><h3 className="font-semibold">Quick Links</h3><div className="mt-5 space-y-3">{(content.quickLinks || []).map((link) => <Link key={link.label} to={link.url} className="block text-sm text-white/60 transition hover:text-white">{link.label}</Link>)}</div></div><div><h3 className="font-semibold">Contact</h3><div className="mt-5 space-y-3 text-sm leading-6 text-white/60">{content.address && <p>{content.address}</p>}{content.email && <a href={`mailto:${content.email}`} className="block hover:text-white">{content.email}</a>}{content.phone && <a href={`tel:${content.phone}`} className="block hover:text-white">{content.phone}</a>}{content.businessHours && <p>{content.businessHours}</p>}{content.mapUrl && <a href={content.mapUrl} target="_blank" rel="noreferrer" className="block text-[var(--footer-accent)]">Google Maps</a>}</div></div><div><h3 className="font-semibold">{content.newsletterTitle || 'Newsletter'}</h3><p className="mt-5 text-sm leading-6 text-white/60">{content.newsletterDescription}</p><form onSubmit={subscribe} className="mt-5 flex gap-2"><input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Email address" className="min-w-0 flex-1 rounded-full border border-white/10 bg-black/20 px-4 py-2.5 text-sm text-white outline-none"/><button className="rounded-full bg-[var(--footer-accent)] px-4 py-2.5 text-sm font-semibold">{content.newsletterButtonText || 'Subscribe'}</button></form>{notice && <p className="mt-3 text-xs text-white/70">{notice}</p>}</div></div><div className="mx-auto flex max-w-7xl flex-col gap-4 border-t border-white/10 px-6 py-6 text-xs text-white/50 lg:flex-row lg:items-center lg:justify-between lg:px-8"><p>{content.copyrightText}</p><div className="flex flex-wrap gap-x-4 gap-y-2">{(content.legalLinks || []).map((link) => <Link key={link.label} to={link.url} className="hover:text-white">{link.label}</Link>)}</div></div></footer>
}
