import React, { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { useProducts } from '../../../hooks/useProducts'

export default function ProductList() {
  const { getProducts, deleteProduct, publishProduct, unpublishProduct } = useProducts()
  const [items, setItems] = useState([]); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all'); const [sort, setSort] = useState('newest'); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('')
  const load = async () => { setLoading(true); setMessage(''); try { const { products } = await getProducts(); setItems(products) } catch (error) { setMessage(error.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const products = useMemo(() => items.filter((item) => `${item.title} ${item.category}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || (filter === 'published' ? item.published : !item.published))).sort((a, b) => sort === 'price' ? Number(a.price) - Number(b.price) : new Date(b.created_at) - new Date(a.created_at)), [items, query, filter, sort])
  const mutate = async (action, success) => { try { await action(); await load(); setMessage(success) } catch (error) { setMessage(error.message) } }
  return <div className="rounded-xl border border-white/10 bg-white/[.055] p-5 shadow-xl backdrop-blur-xl"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-bold text-white">Product Catalog</h2><p className="text-sm text-text-muted">{items.length} products</p></div><div className="flex gap-2"><button onClick={load} className="rounded-lg border border-white/10 px-3 py-2 text-sm">Refresh</button><Link to="/admin/products/add" className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white">Add Product</Link></div></div><div className="mb-5 grid gap-3 md:grid-cols-3"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search products" className="rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-sm text-white"/><select value={filter} onChange={(e) => setFilter(e.target.value)} className="rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-sm text-white"><option value="all">All statuses</option><option value="published">Published</option><option value="draft">Draft</option></select><select value={sort} onChange={(e) => setSort(e.target.value)} className="rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-sm text-white"><option value="newest">Newest</option><option value="price">Price low to high</option></select></div>{message && <p className="mb-4 rounded-lg border border-white/10 bg-white/5 p-3 text-sm text-white">{message}</p>}{loading ? <p className="p-6 text-text-muted">Loading products…</p> : !products.length ? <p className="rounded-lg border border-white/10 p-6 text-text-muted">No products found.</p> : <div className="space-y-3">{products.map((product) => <div key={product.id} className="flex flex-col gap-4 rounded-lg border border-white/10 bg-black/15 p-4 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-4"><img src={product.thumbnail || '/assets/images/og-icon-editz.png'} alt="" className="h-16 w-24 rounded-lg object-cover"/><div><p className="font-semibold text-white">{product.title}</p><p className="text-sm text-text-muted">{product.category || 'Uncategorized'} · ₹{product.discountPrice ?? product.price}</p></div></div><div className="flex gap-3"><button onClick={() => mutate(() => product.published ? unpublishProduct(product.id) : publishProduct(product.id), 'Product status updated.')} className="text-sm text-primary">{product.published ? 'Draft' : 'Publish'}</button><Link to={`/admin/products/${product.id}/edit`} className="text-sm text-primary">Edit</Link><button onClick={() => window.confirm(`Delete “${product.title}”?`) && mutate(() => deleteProduct(product.id), 'Product deleted.')} className="text-sm text-red-300">Delete</button></div></div>)}</div>}</div>
}
