import React, { useEffect, useState } from 'react'
import { request } from '../../utils/api'

export default function CategoriesPage() {
  const [items, setItems] = useState([]); const [name, setName] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  const load = async () => { setLoading(true); try { const response = await request('/api/categories'); setItems(response.data || []); setError('') } catch (error) { setError(error.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const add = async (event) => { event.preventDefault(); if (!name.trim()) return setError('Category name is required.'); try { await request('/api/categories', { method: 'POST', body: { name: name.trim() } }); setName(''); load() } catch (error) { setError(error.message) } }
  const remove = async (id) => { if (!window.confirm('Delete this category?')) return; try { await request(`/api/categories?id=${encodeURIComponent(id)}`, { method: 'DELETE' }); setItems((current) => current.filter((item) => item.id !== id)) } catch (error) { setError(error.message) } }
  return <div className="max-w-3xl rounded-xl border border-white/10 bg-white/[.055] p-6 shadow-xl backdrop-blur-xl"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-bold text-white">Categories</h2><p className="mt-1 text-sm text-text-muted">Create and manage product categories.</p></div><button onClick={load} className="rounded-lg border border-white/10 px-3 py-2 text-sm">Refresh</button></div><form onSubmit={add} className="mt-6 flex gap-3"><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Category name" className="flex-1 rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-white"/><button className="rounded-lg bg-primary px-4 py-2 font-semibold text-white">Add Category</button></form>{error && <p className="mt-4 text-sm text-red-300">{error}</p>}{loading ? <p className="mt-6 text-text-muted">Loading categories…</p> : <div className="mt-6 space-y-2">{items.length ? items.map((item) => <div key={item.id} className="flex items-center justify-between rounded-lg border border-white/10 p-3"><span>{item.name}</span><button onClick={() => remove(item.id)} className="text-sm text-red-300">Delete</button></div>) : <p className="text-text-muted">No categories yet.</p>}</div>}</div>
}
